server:
  port: 7003

eureka:
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称
  client:
    register-with-eureka: false #false表示不向注册中心注册自己
    fetch-registry: false #fasle表示自己就是注册中心，我的职责就是维护服务实例，并不需要在注册中心检索到我（这个服务）
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  #(单机版)设置Eureka Server交互的地址，查询服务和注册服务都要依赖这个地址
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/